import { Client } from '@neondatabase/serverless';
import fs from 'fs';

const env = fs.readFileSync('.env', 'utf8');
const config = {};
env.split('\n').forEach(l => {
  const parts = l.split('=');
  if (parts.length >= 2) {
    config[parts[0].trim()] = parts.slice(1).join('=').trim();
  }
});

const connectionString = config.DATABASE_URL;
const baseUrl = 'http://127.0.0.1:3000';

async function main() {
  console.log('--- STARTING WATERING SCHEDULER CRON EXECUTION INTEGRATION TESTS ---');

  const client = new Client({ connectionString });
  await client.connect();

  let createdScheduleId = null;

  try {
    // 1. Get system timezone
    const tzRes = await client.query("SELECT value FROM system_config WHERE key = 'timezone'");
    const timezone = tzRes.rows[0]?.value || 'Europe/Bucharest';
    console.log(`[Config] Using timezone: ${timezone}`);

    // Define static test schedule parameters
    const timeOfDay = '08:00:00';
    const localDayOfWeek = 2; // Tuesday

    console.log(`[Status] Using deterministic simulated test schedule: ${timeOfDay} | Day: Tuesday (${localDayOfWeek})`);

    // 2. Set up a test schedule matching the current local minute
    console.log('\n[Step 1] Creating temporary schedule matching current time...');
    const schedRes = await client.query(
      `INSERT INTO watering_schedules (pump_ids, time_of_day, duration_seconds, days_of_week, enabled)
       VALUES (ARRAY[1], $1, 60, ARRAY[$2::int], true) RETURNING id`,
      [timeOfDay, localDayOfWeek]
    );
    createdScheduleId = schedRes.rows[0].id;
    console.log(`Created test schedule ID: ${createdScheduleId}`);

    // Ensure pump 1 state is initially 0
    await client.query('UPDATE pump_configs SET state = 0 WHERE id = 1');

    // 3. Trigger Cron Run
    console.log('\n[Step 2] Executing cron runner GET /api/cron/run?simulated_time=08:00&simulated_day=2...');
    const triggerRes = await fetch(`${baseUrl}/api/cron/run?simulated_time=08:00&simulated_day=2`);
    const triggerBody = await triggerRes.json();
    console.log('Cron response:', triggerBody);

    if (triggerRes.status !== 200 || !triggerBody.success) {
      throw new Error('Cron execution failed.');
    }

    // Verify that Pump 1 has been triggered ON
    const trigger = triggerBody.triggers.find(t => t.pumpId === 1);
    if (!trigger || trigger.status !== 'triggered_on') {
      throw new Error('Pump 1 was not successfully triggered ON.');
    }
    console.log('SUCCESS: Pump 1 was successfully triggered ON by the scheduler!');

    // Check pump_configs state is now 1
    const pumpStateRes = await client.query('SELECT state FROM pump_configs WHERE id = 1');
    console.log('Pump 1 current state in database:', pumpStateRes.rows[0].state);
    if (pumpStateRes.rows[0].state !== 1) {
      throw new Error('Pump 1 state was not updated to 1 in configuration.');
    }

    // 4. Simulate duration expiration by updating command_logs timestamp back in time
    console.log('\n[Step 3] Simulating duration expiration (updating ON timestamp to 5 minutes ago)...');
    const updateRes = await client.query(
      `UPDATE command_logs 
       SET created_at = NOW() - INTERVAL '5 minutes'
       WHERE pump = 1 AND state = 1 AND status = 'success'
       RETURNING id, created_at`
    );
    console.log('Updated ON log details:', updateRes.rows[0]);

    // 5. Trigger Cron Run (Sweeper Check)
    console.log('\n[Step 4] Executing cron runner (OFF Sweeper) GET /api/cron/run...');
    const sweepRes = await fetch(`${baseUrl}/api/cron/run`);
    const sweepBody = await sweepRes.json();
    console.log('Cron response (sweeper):', sweepBody);

    if (sweepRes.status !== 200 || !sweepBody.success) {
      throw new Error('Cron sweeper execution failed.');
    }

    // Verify that Pump 1 has been swept OFF
    const sweep = sweepBody.sweeps.find(s => s.pumpId === 1);
    if (!sweep || sweep.status !== 'swept_off') {
      throw new Error('Pump 1 was not swept OFF.');
    }
    console.log('SUCCESS: Pump 1 was successfully swept OFF by the sweeper!');

    // Check pump_configs state is back to 0
    const finalStateRes = await client.query('SELECT state FROM pump_configs WHERE id = 1');
    console.log('Pump 1 final state in database:', finalStateRes.rows[0].state);
    if (finalStateRes.rows[0].state !== 0) {
      throw new Error('Pump 1 final state did not reset to 0.');
    }

  } catch (err) {
    console.error('\nTEST FAILED:', err.message);
    process.exitCode = 1;
  } finally {
    console.log('\n[Cleanup] Cleaning up database test records...');
    if (createdScheduleId) {
      await client.query('DELETE FROM watering_schedules WHERE id = $1', [createdScheduleId]);
    }
    // Delete test command log records generated by this run
    await client.query("DELETE FROM command_logs WHERE pump = 1 AND created_at > NOW() - INTERVAL '15 minutes'");
    await client.end();
    console.log('--- TEST RUN COMPLETED ---');
  }
}

main();
